baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Mosey Podcast'
primary: true
siteGroup: 3f4cc2e9-4911-41d2-9bb7-3c74b37d402a # Mosey Podcast
sortOrder: 1
