columnSuffix: czqpylds
contentColumnType: text
fieldGroup: 246d7e21-bfd5-4b86-95f6-6a1f83d49ce3 # Common
handle: callToAction
instructions: ''
name: 'Call To Action'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Call to Action Text'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
