columnSuffix: null
contentColumnType: string
fieldGroup: 246d7e21-bfd5-4b86-95f6-6a1f83d49ce3 # Common
handle: container
instructions: ''
name: Container
searchable: false
settings:
  contentTable: '{{%stc_container}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
