columnSuffix: null
contentColumnType: string
fieldGroup: 246d7e21-bfd5-4b86-95f6-6a1f83d49ce3 # Common
handle: latestContent
instructions: 'This will show the most recent episode, links to it on the major platforms, and the option to listen here.'
name: 'Latest Content'
searchable: false
settings:
  contentTable: '{{%stc_latestcontent}}'
  fieldLayout: row
  maxRows: '1'
  minRows: '1'
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
