columnSuffix: okhhmcgu
contentColumnType: text
fieldGroup: 246d7e21-bfd5-4b86-95f6-6a1f83d49ce3 # Common
handle: textBlock
instructions: 'This is a simple block of text, potentially used to tell more about the podcast.'
name: 'Text Block'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Text Block'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
