field: 4de8c2f6-602b-4b53-90a0-e1890aba309e # Latest Content
fieldLayouts:
  d24465a8-36da-4053-a740-be723dee5bc3:
    tabs:
      -
        elements:
          -
            fieldUid: 417fd695-3865-4a13-9472-e089651c22fe # Audio
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5f7efe5c-f33e-4a34-b484-3cce991f1d31 # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 834b4231-6986-427b-996b-ef52769b0f1c # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5f7efe5c-f33e-4a34-b484-3cce991f1d31: # Thumbnail
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: thumbnail
    instructions: ''
    name: Thumbnail
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:17d2fe99-f345-4936-8a61-8f10d7fe53ef' # First Volume
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add a Thumbnail'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:17d2fe99-f345-4936-8a61-8f10d7fe53ef' # First Volume
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  417fd695-3865-4a13-9472-e089651c22fe: # Audio
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: audio
    instructions: ''
    name: Audio
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - audio
      defaultUploadLocationSource: 'volume:17d2fe99-f345-4936-8a61-8f10d7fe53ef' # First Volume
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add Audio File'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:17d2fe99-f345-4936-8a61-8f10d7fe53ef' # First Volume
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  834b4231-6986-427b-996b-ef52769b0f1c: # Description
    columnSuffix: btvprwtt
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
