defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  c6e56abd-82dd-495b-bda7-fa82edcbe5da: # Mosey Podcast
    enabledByDefault: true
    hasUrls: true
    template: _pages/home
    uriFormat: __home__
type: single
