defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  181f615e-f62a-4b86-9006-4caf737fd872: # craftSite
    enabledByDefault: true
    hasUrls: true
    template: _pages/home
    uriFormat: __home__
type: single
